INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (1, 'test');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (33, 'AYEfghs');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (34, 'werty');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (35, 'Bonteavond');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (36, 'Thijs Geurts');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (37, 'Thijs Geurts');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (38, 'ytyy');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (39, 'ytyy');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (40, 'ytfh');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (41, 'Test');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (42, 'test');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (43, 'g');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (44, 'f');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (45, 'g');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (46, 'g');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (47, 'gfd');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (48, 'DE');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (49, 't');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (50, 't');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (51, 'gfd');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (52, 'gfd');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (53, 'gfd');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (54, 'gfd');
INSERT INTO roosterit.rooster (roosterId, roosterName) VALUES (55, 'f');